Feature/arrays and devs
cmdotcom/text-sdk-java pull request #17
Opened 2022-10-18 14:39 UTC by EnessenE

2022-11-07 17:16 UTC, EnessenE commented
Issue #13 Tested and fixed

2022-11-08 11:32 UTC, EricSmekens approved these changes

2022-11-08 11:34 UTC, EricSmekens requested changes

2022-11-08 11:34 UTC, EricSmekens commented on src/main/java/com/cm/text/models/multichannel/RichContent.java
> +            newArr = Arrays.copyOf(newArr, this.Conversation.length + 1 );
```suggestion
            newArr = Arrays.copyOf(newArr, this.Suggestions.length + 1 );
```

2022-11-09 10:52 UTC, EricSmekens approved these changes

2022-11-10 10:37 UTC, merged