Add twitter channel
cmdotcom/text-sdk-java pull request #7
Opened 2020-05-12 14:36 UTC by michaelvdnet

Updated library for twitter.

Merge after Twitter goes live.

2020-05-27 07:21 UTC, michaelvdnet commented
@EricSmekens This merge request is ready to be merged!

2020-05-28 14:16 UTC, EricSmekens requested changes

2020-05-28 14:16 UTC, EricSmekens commented on src/main/java/com/cmtelecom/text/sdk/models/Channel.java
> +    ///     Messages will be sent over Line.
There is copy-paste error here.

2020-06-02 08:01 UTC, EricSmekens approved these changes

2020-06-02 08:02 UTC, merged